sudo: required

language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: utplsql
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - develop
      - master
      - test_ut_run_script

env:
  global:
    #Oracle 11g XE R2 docker variables
    - ORACLE_VERSION=11g-r2-xe
    - CONNECTION_STR='127.0.0.1:1521/XE'
    - DOCKER_OPTIONS='--shm-size=1g'
    # Docker database Env
    - SQLCLI="$HOME/sqlcl/bin/sql"
    - OJDBC_HOME="$HOME/sqlcl/lib"
    - ORACLE_PWD="oracle"
    - UT3_DOCKER_REPO="utplsqlv3/oracledb"
    - DOCKHER_HUB_REPO="${DOCKER_BASE_TAG:-$UT3_DOCKER_REPO}"
    # project variables
    - DB_USER=ut3_demo
    - DB_PASS=LHZYPbWvYdu2ctp8
    ##utPLSQL variables
    - UTPLSQL_DIR="utPLSQL"
    - ORA_SDTZ='Europe/London' #Needed as a client parameter
    - TZ='Europe/London'       #Needed as a DB Server parameter
    ##utPLSQL-cli variables
    - UTPLSQL_CLI_VERSION="3.1.0"
    - CACHE_DIR=$HOME/.cache
    - MAVEN_HOME=/usr/local/maven
    - MAVEN_CFG=$HOME/.m2
  matrix:
    - UTPLSQL_3_VERSION='develop'
    - UTPLSQL_3_VERSION='v3.0.0' VERSION_PLACEHOLDER='utPLSQL - Version X.X.X.X'
    - UTPLSQL_3_VERSION='v3.0.4' VERSION_PLACEHOLDER='X.X.X.X'
    - UTPLSQL_3_VERSION='v3.1.1'

cache:
  pip: true
  directories:
    - $CACHE_DIR
    - node_modules
    - $MAVEN_CFG

before_install:
  # download latest utPLSQL develop code
  - git clone --depth=1 --branch=${UTPLSQL_3_VERSION} https://github.com/utPLSQL/utPLSQL.git ${UTPLSQL_DIR}
  # download latest utPLSQL-cli release
  - curl -Lk -o utPLSQL-cli.zip https://github.com/utPLSQL/utPLSQL-cli/releases/download/v${UTPLSQL_CLI_VERSION}/utPLSQL-cli.zip
  # update version placeholder before install
  - if [[ -n ${VERSION_PLACEHOLDER} ]] ; then sed -i "s/${VERSION_PLACEHOLDER}/${UTPLSQL_3_VERSION}/g" ${UTPLSQL_DIR}/source/core/ut_utils.pks; fi


install:
  - unzip utPLSQL-cli.zip && chmod -R u+x utPLSQL-cli
  # get ojdbc.jar from Oracle using maven
  - bash .travis/maven_cfg.sh
  - bash .travis/install_sqlcl.sh
  # download and run Oracle docker DB image
  - bash .travis/start_db.sh

  # Install utPLSQL
  - .travis/install_utplsql.sh
  - .travis/setup_account.sh
  # Install project sources and tests
  - source/install.sh
  - test/install.sh

script:
  # Run tests
  - test/run.sh
  # Run sonar scanner and publish to sonar
  - sonar-scanner
