sudo: required

language: java
jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: utplsql
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - develop
      - master

env:
  global:
    #Oracle 11g XE R2 variables
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    #Adding SQLPlus to path
    - PATH=$PATH:$ORACLE_HOME/bin
    # project variables
    - DB_USER=ut3_demo
    - DB_PASS=LHZYPbWvYdu2ctp8
    ##utPLSQL variables
    - UTPLSQL_DOWNLOAD_URL=$(curl --silent https://api.github.com/repos/utPLSQL/utPLSQL/releases/latest | awk '/browser_download_url/ { print $2 }' | grep ".zip" | sed 's/"//g')
    - UTPLSQL_DOWNLOAD_FILE="${UTPLSQL_DOWNLOAD_URL##*/}"
    - UTPLSQL_DIR="${UTPLSQL_DOWNLOAD_FILE%.*}"
before_install:
  - npm install -g phantomjs-prebuilt casperjs
  # download Oracle XE installer for Travis
  - .travis/oracle/download.sh
  # download utPLSQL
  - curl -LOk "${UTPLSQL_DOWNLOAD_URL}"
  - unzip -q "${UTPLSQL_DOWNLOAD_FILE}"
  - cp ${UTPLSQL_DIR}/client_source/sqlplus/ut_run.sql .

install:
  # Install Oracle Database
  - .travis/oracle/install.sh
  # Install utPLSQL
  - .travis/install_utplsql.sh
  - .travis/setup_account.sh
  # Instal project sources and tests
  - source/install.sh
  - test/install.sh

script:
  # Run tests
  - test/run.sh
  # Run sonar scanner and publish to sonar
  - sonar-scanner
