sudo: required

language: java
jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: utplsql
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - develop
      - master
      - test_ut_run_script

env:
  global:
    #Oracle 11g XE R2 variables
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    #Adding SQLPlus to path
    - PATH=$PATH:$ORACLE_HOME/bin
    # project variables
    - DB_USER=ut3_demo
    - DB_PASS=LHZYPbWvYdu2ctp8
    ##utPLSQL variables
    - UTPLSQL_DIR="utPLSQL"
    - ORA_SDTZ='Europe/London' #Needed as a client parameter
    - TZ='Europe/London'       #Needed as a DB Server parameter
before_install:
  - npm install -g phantomjs-prebuilt casperjs
  # download Oracle XE installer for Travis
  - .travis/oracle/download.sh
  # download latest utPLSQL release
  - curl -LOk $(curl --silent https://api.github.com/repos/utPLSQL/utPLSQL/releases/latest | awk '/browser_download_url/ { print $2 }' | grep ".zip" | sed 's/"//g')
  # download utPLSQL-cli develop
  - curl -Lk -o utPLSQL-cli.zip https://bintray.com/viniciusam/utPLSQL-cli/download_file?file_path=utPLSQL-cli-develop-201706191645.zip

install:
  - unzip utPLSQL.zip
  - unzip utPLSQL-cli.zip
  # Install Oracle Database
  - .travis/oracle/install.sh
  # Install utPLSQL
  - .travis/install_utplsql.sh
  - .travis/setup_account.sh
  # Instal project sources and tests
  - source/install.sh
  - test/install.sh

script:
  # Run tests
  - test/run.sh
  - utPLSQL-cli/bin/utplsql run ${DB_USER}/${DB_PASS} -source_path=source -test_path=test -f=ut_documentation_reporter -c -f=ut_coverage_sonar_reporter -o=coverage.xml -f=ut_sonar_test_reporter -o=test_results.xml
  # Run sonar scanner and publish to sonar
  - sonar-scanner
