sudo: required

language: java
jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: utplsql
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - develop
      - master

env:
  global:
    #Oracle 11g XE R2 variables
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    #Adding SQLPlus to path
    - PATH=$PATH:$ORACLE_HOME/bin
    # utPLSQL variables
    - UTPLSQL_VERSION="v3.0.0-beta"
    - UTPLSQL_FILE="utPLSQLv3.0.0.562-beta"
    # project variables
    - DB_USER=ut3_demo
    - DB_PASS=LHZYPbWvYdu2ctp8
    - UTPLSQL_DOWNLOAD_FILE_TYPE='gz' # either 'zip' or 'gz' is available
    #Go envi variables
    - GOPATH=${TRAVIS_BUILD_DIR}
before_install:
  ## get odl (Oracle Download Utility)
  - go get github.com/tschf/odl
  ## download Oracle XE installer for Travis
  - odl --component db --version 11gXE --os linux --arch x64
  ## download utPLSQL
  - curl -LOk `curl --silent https://api.github.com/repos/utPLSQL/utPLSQL/releases/latest | awk '/browser_download_url/ { print $2 }' | grep ".${UTPLSQL_DOWNLOAD_FILE_TYPE}" | sed 's/"//g'`
  - tar -xzf ${UTPLSQL_FILE}.tar.gz
  - cp ${UTPLSQL_FILE}/client_source/sqlplus/ut_run.sql .

install:
  # Install Oracle Database
  - .travis/oracle/install.sh
  # Install utPLSQL
  - .travis/install_utplsql.sh
  - .travis/setup_account.sh
  # Instal project sources and tests
  - source/install.sh
  - test/install.sh

script:
  # Run tests
  - test/run.sh
  # Run sonar scanner and publish to sonar
  - sonar-scanner
