# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - develop

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: utplsql/oracledb:11g-r2-xe
  endpoint: utPLSQL-docker

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: "8"

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
