# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - develop

pool:
  vmImage: 'ubuntu-16.04'

variables:
  DOCKHER_HUB_REPO: 'utplsqlv3/oracledb'
  ORACLE_VERSION: '11g-r2-xe'
  CONNECTION_STR: '127.0.0.1:1521/XE'
  DOCKER_OPTIONS: '--shm-size=1g'

steps:
- script: |
    docker login -u $(DOCKER_USER) -p $(DOCKER_PASSWORD)
    # download Oracle Database docker image from private repo and start the DB
    time docker pull ${DOCKHER_HUB_REPO}:${ORACLE_VERSION}
    # start the docker container (DB)
    docker run -d --name ${ORACLE_VERSION} ${DOCKER_OPTIONS} -p 1521:1521 ${DOCKHER_HUB_REPO}:${ORACLE_VERSION}
    # Wait for DB startup
    time docker logs -f ${ORACLE_VERSION} | grep -m 1 "DATABASE IS READY TO USE!" --line-buffered

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
